/**
 * @file location.js
 * @project PathPal App
 * @description
 *   Obtains the user’s current location via the Geolocation API and fetches local weather data
 *   from OpenWeatherMap. Updates the UI with city name, weather icon, temperature, and description.
 * @author PathPal Team
 * @ai Use
 *   Portions of this code were generated by AI as a learning aid and have been reviewed and refined
 *   to align with PathPal’s design and functionality requirements.
 *
 * Sections:
 *   1. Feature Detection & Geolocation Request
 *   2. Error Handling
 *   3. Success Handler & Weather Fetch
 */

// 1. Feature Detection & Geolocation Request
if (!navigator.geolocation) {
  console.warn('Geolocation not supported');
} else {
  navigator.geolocation.getCurrentPosition(onSuccess, onError, {
    enableHighAccuracy: true,
    timeout: 10000,
    maximumAge: 0
  });
}

// 2. Error Handling
/**
 * Logs any error encountered while attempting to obtain the user’s position.
 * @param {PositionError} err – Error object from Geolocation API
 */
function onError(err) {
  console.error('Geolocation error:', err);
}

// 3. Success Handler & Weather Fetch
/**
 * Called when the user’s location is successfully obtained.
 * Rounds coordinates, fetches weather data, and updates UI elements.
 * @param {GeolocationPosition} position – Position object from Geolocation API
 */
async function onSuccess(position) {
  const lat = position.coords.latitude.toFixed(4);
  const lon = position.coords.longitude.toFixed(4);
  const apiKey = '26c5adb12406f436f381157dadc63935';

  try {
    // Fetch current weather for the obtained coordinates
    const resp = await fetch(
      `https://api.openweathermap.org/data/2.5/weather?` +
      `lat=${lat}&lon=${lon}&units=metric&appid=${apiKey}`
    );
    const data = await resp.json();
    // Update UI: city name
    document.getElementById('city').textContent = data.name;
    // Update UI: weather icon
    const icon = data.weather[0].icon;
    document.getElementById('weather-icon').src =
      `https://openweathermap.org/img/wn/${icon}@2x.png`;
    // Update UI: temperature
    document.getElementById('temp').textContent =
      `${Math.round(data.main.temp)}°C`;
    // Update UI: weather description
    document.getElementById('description').textContent =
      data.weather[0].description;
  } catch (e) {
    console.error('Weather fetch error:', e);
  }
}
