/**
 * @file map.js
 * @project PathPal App
 * @description JavaScript for PathPal map feature: initializes Mapbox map, loads boundary and POIs,
 * sets up controls (navigation, geolocation, traffic, voice, POI toggles), handles directions, POI addition,
 * and voting functionality.
 * @ai Use: This file leverages AI as a learning tool. Portions of this code were generated by AI and subsequently modified to align with PathPal's
 * functionality requirements and project conventions.
 * @author PathPal Team
 *
 * Sections:
 *   1. Imports & Access Token
 *   2. Global Variables & Marker Arrays
 *   3. Map Initialization & Profile Mapping
 *   4. VoiceControl Class
 *   5. Map 'load' Event: Icon Loading, Sources & Layers, UI Controls
 *   6. Add-POI Feature Initialization
 *   7. Mode-tab & Route Handling
 *   8. Boundary & POI Loading Functions
 *   9. Marker Creation Utility
 *  10. ToggleControl Class
 *  11. Global Event Delegation & Exports
 */

// 1. Imports & Access Token
import { initDirections } from './mapDirections.js';
import { setupAddPOIFeature } from './addPoi.js';
import { createPopup } from './popup.js';
import { loadSavedRoutes } from './loadSavedRoute.js';
import { applyPOITargetFromURL, autoFillEndInputFromURL, applySavedRouteFromURL } from './mapRouteFromURL.js';
import { handleVoteClick } from '../utils/vote.js';

mapboxgl.accessToken = window.MAPBOX_TOKEN;

// 2. Global Variables & Marker Arrays
let lastOrigin = null;
let lastDestination = null;

const wheelchairMarkers = [];
const seniorMarkers = [];
const userPOIMarkers = [];

window.userPOIMarkers = userPOIMarkers;

// 3. Map Initialization & Profile Mapping
const map = new mapboxgl.Map({
  container: 'map',
  style: 'mapbox://styles/mapbox/streets-v11',
  center: [-123.037605, 49.226791],
  zoom: 11
});

window.pathpalMap = map;

let filterWheelchair = false;
let filterSenior = false;
let filterUserPOI = false;


// 4. VoiceControl Class
class VoiceControl {
  constructor(onToggle) {
    this.onToggle = onToggle;
    this.enabled = false;
  }
  onAdd(map) {
    this.map = map;
    this.container = document.createElement('div');
    this.container.className = 'mapboxgl-ctrl mapboxgl-ctrl-group';

    this.btn = document.createElement('button');
    this.btn.type = 'button';
    this.btn.className = 'mapboxgl-ctrl-icon';
    this.btn.setAttribute('aria-label', 'Toggle voice guidance');
    this.btn.textContent = '🔊';
    this.btn.style.opacity = '0.4';

    this.btn.addEventListener('click', () => {
      this.enabled = !this.enabled;
      this.btn.style.opacity = this.enabled ? '1.0' : '0.4';
      window.voiceGuidanceEnabled = this.enabled;
    });

    this.container.appendChild(this.btn);
    return this.container;
  }
  onRemove() {
    this.container.remove();
    this.map = null;
  }
}

const profileMap = {
  driving: 'mapbox/driving',
  walking: 'mapbox/walking',
  senior: 'mapbox/walking',
  wheelchair: 'mapbox/cycling'
};

// 5. Map 'load' Event: Icon Loading, Sources & Layers, UI Controls
map.on('load', () => {
  // Load custom icons
  map.loadImage('/icons/restroom.png', (err, img) => {
    if (err) {
      console.error('restroom.png load failed:', err);
      return;
    }
    map.addImage('custom-restroom', img);
  });

  map.loadImage('/icons/bench.png', (err, img) => {
    if (err) {
      console.error('Failed to load bench icon:', err);
      return;
    }
    if (!map.hasImage('bench-15')) {
      map.addImage('bench-15', img);
    }
  });

  map.loadImage('/icons/ramp.png', (err, img) => {
    if (err) return console.error('ramp.png load error', err);
    if (!map.hasImage('ramp-15')) map.addImage('ramp-15', img);
  });

  // Add traffic source & layer
  map.addSource('traffic', {
    type: 'vector',
    url: 'mapbox://mapbox.mapbox-traffic-v1'
  });
  map.addLayer({
    id: 'traffic-layer',
    type: 'line',
    source: 'traffic',
    'source-layer': 'traffic',
    layout: {
      'line-join': 'round',
      'line-cap': 'round',
      visibility: 'none'
    },
    paint: {
      'line-color': [
        'match',
        ['get', 'congestion'],
        'low', '#2DC4B2',
        'moderate', '#FFFF00',
        'heavy', '#FF0000',
        /*default*/ '#000000'
      ],
      'line-width': 2
    }
  });

  // Toggle listener for turn-by-turn panel
  const turnBox = document.getElementById('turn-by-turn');
  const showTurnBtn = document.getElementById('btn-show-turns');
  const hideTurnBtn = document.getElementById('btn-toggle-turns');

  if (turnBox && showTurnBtn && hideTurnBtn) {
    // Hide/Show the panel
    hideTurnBtn.addEventListener('click', () => {
      turnBox.classList.add('d-none');
      showTurnBtn.classList.remove('d-none');
    });

    showTurnBtn.addEventListener('click', () => {
      turnBox.classList.remove('d-none');
      showTurnBtn.classList.add('d-none');
    });
  }

  // Built‑in navigation & geolocate 
  map.addControl(new mapboxgl.NavigationControl(), 'top-right');
  map.addControl(new mapboxgl.GeolocateControl({
    positionOptions: { enableHighAccuracy: true },
    trackUserLocation: true,
    showUserHeading: true
  }), 'top-right');

  // Traffic Toggle Button
  const trafficBtn = document.createElement('button');
  trafficBtn.className = 'mapboxgl-ctrl-icon';
  trafficBtn.setAttribute('aria-label', 'Toggle traffic');
  trafficBtn.textContent = '🚦';
  trafficBtn.style.fontSize = '18px';
  trafficBtn.addEventListener('click', () => {
    const vis = map.getLayoutProperty('traffic-layer', 'visibility');
    map.setLayoutProperty(
      'traffic-layer',
      'visibility',
      vis === 'none' ? 'visible' : 'none'
    );
  });
  const trafficControl = {
    onAdd() {
      this._container = document.createElement('div');
      this._container.className = 'mapboxgl-ctrl mapboxgl-ctrl-group';
      this._container.appendChild(trafficBtn);
      return this._container;
    },
    onRemove() {
      this._container.parentNode.removeChild(this._container);
    }
  };
  map.addControl(trafficControl, 'top-right');

  // Voice toggle control
  const voiceControl = new VoiceControl(enabled => {
    window.voiceGuidanceEnabled = enabled;
  });
  map.addControl(voiceControl, 'top-right');

  // POI Toggle Controls
  const wcCtrl = new ToggleControl('wheelchair', wheelchairMarkers, visible => {
    filterWheelchair = visible;
    loadPOIs();
  });
  const srCtrl = new ToggleControl('senior', seniorMarkers, visible => {
    filterSenior = visible;
    loadPOIs();
  });
  const userPOICtrl = new ToggleControl('poi', userPOIMarkers, visible => {
    filterUserPOI = visible;
    loadPOIs();
  });
  map.addControl(wcCtrl, 'top-right');
  map.addControl(srCtrl, 'top-right');
  map.addControl(userPOICtrl, 'top-right');

  // Draw boundary & load initial POIs ───
  loadBoundary();
  loadPOIs();

  // Reload POIs on pan/zoom
  map.on('moveend', () => {
    if (filterWheelchair || filterSenior || filterUserPOI) {
      loadPOIs();
    }
  });

  // Initialize directions ───
  const directions = initDirections(map, {
    onRouteSet: ({ origin, destination }) => {
      lastOrigin = origin;
      lastDestination = destination;
    }
  });
  window.pathpalDirections = directions;

  // Get profile param from saved routes
  const profileFromURL = new URLSearchParams(window.location.search).get('profile');
  if (profileFromURL) {
    directions.setProfile(profileFromURL);

    // Highlight the correct tab
    document.querySelectorAll('#mode-buttons button').forEach(btn => {
      const mode = btn.dataset.mode;
      btn.classList.toggle('active', mode === profileFromURL);
    });
  }

  Object.entries(profileMap).forEach(([mode, profile]) => {
    const tab = document.getElementById(`${mode}Tab`);
    if (!tab) return;
    tab.addEventListener('click', () => {
      // Trigger save route prompt if available
      if (typeof window.triggerSaveRoutePrompt === 'function') {
        window.triggerSaveRoutePrompt();
      }

      directions.setProfile(profile);
      if (lastOrigin && lastDestination) {
        directions.setOrigin(lastOrigin);
        directions.setDestination(lastDestination);
      }
    });
  });

  loadSavedRoutes(map);

  // Get lat and lng from POI post and auto fill End address input field
  const params = new URLSearchParams(window.location.search);
  const type = params.get('type');
  if (type === 'user-poi') {
    applyPOITargetFromURL(map);
    autoFillEndInputFromURL();
  }
  if (type === 'savedRoutes') {
    applySavedRouteFromURL(map, directions);
  }
});

// 6. Add-POI Feature Initialization
setupAddPOIFeature();

// 7. Mode-tab click handlers
const closeDirBtn = document.getElementById('btn-close-directions');
if (closeDirBtn) {
  closeDirBtn.addEventListener('click', () => {
    document.getElementById('directions-panel')?.classList.add('d-none');
  });
}

// 8. Boundary & POI Loading Functions
async function loadBoundary() {
  try {
    const res = await fetch('/data/metro-vancouver-boundaries.geojson');
    const geo = await res.json();
    const fc = turf.featureCollection(geo.features);
    const hull = turf.convex(fc);
    if (!hull) throw new Error('Convex hull failed');

    if (!map.getSource('boundary')) {
      map.addSource('boundary', { type: 'geojson', data: hull });
      map.addLayer({
        id: 'boundary-line',
        type: 'line',
        source: 'boundary',
        layout: { 'line-join': 'round', 'line-cap': 'round' },
        paint: { 'line-color': '#FF0000', 'line-width': 2 }
      });
    } else {
      map.getSource('boundary').setData(hull);
    }
  } catch (err) {
    console.error('Boundary error:', err);
  }
}

async function loadPOIs() {
  //clear out old markers
  wheelchairMarkers.forEach(m => m.remove());
  seniorMarkers.forEach(m => m.remove());
  userPOIMarkers.forEach(m => m.remove());
  wheelchairMarkers.length = seniorMarkers.length = userPOIMarkers.length = 0;

  //viewport bounds
  const bounds = map.getBounds();

  try {
    if (filterWheelchair) {
      const res = await fetch('/data/wheelchair-friendly.geojson');
      const geo = await res.json();
      const inView = geo.features.filter(f => {
        const coords = (f.geometry.type === 'Point')
          ? f.geometry.coordinates
          : turf.centroid(f).geometry.coordinates;
        return bounds.contains(coords);
      });
      makeMarkers(inView, wheelchairMarkers, 'wheelchair');
    }

    if (filterSenior) {
      const res = await fetch('/data/senior-friendly.geojson');
      const geo = await res.json();
      const inView = geo.features.filter(f => {
        const coords = (f.geometry.type === 'Point')
          ? f.geometry.coordinates
          : turf.centroid(f).geometry.coordinates;
        return bounds.contains(coords);
      });
      makeMarkers(inView, seniorMarkers, 'senior');
    }

    //User‐added POIs
    if (filterUserPOI) {
      const res = await fetch('/api/poi/markers');
      const data = await res.json();
      const features = data.map(poi => ({
        type: 'Feature',
        geometry: poi.coordinates,
        properties: { ...poi }
      }));
      const inView = features.filter(f => {
        const coords = f.geometry.coordinates;
        return bounds.contains(coords);
      });
      makeMarkers(inView, userPOIMarkers, 'poi');
    }
  } catch (err) {
    console.error('POI load error:', err);
  }
}

// 9. Marker Creation Utility
function makeMarkers(features, list, icon) {
  for (const f of features) {
    const coords = f.geometry.type === 'Point'
      ? f.geometry.coordinates
      : turf.centroid(f).geometry.coordinates;

    const [lng, lat] = coords;

    const el = document.createElement('div');
    el.className = 'custom-marker';
    el.style.backgroundImage = `url(/icons/${icon}.png)`;
    el.style.width = '32px';
    el.style.height = '32px';
    el.style.backgroundSize = 'contain';

    const popup = createPopup({
      coordinates: [lng, lat],
      properties: {
        ...f.properties,
        image: f.properties.imageUrl
      }
    });
    
    // Hover listeners
el.addEventListener('click', () => {
  // Close all existing popups
  document.querySelectorAll('.mapboxgl-popup').forEach(p => p.remove());

  // Add the popup on click
  popup.addTo(map).setLngLat([lng, lat]);

  setTimeout(() => {
    const btn = document.querySelector('.get-directions-btn');
    if (btn) {
      btn.addEventListener('click', () => {
        const lng = parseFloat(btn.dataset.lng);
        const lat = parseFloat(btn.dataset.lat);

        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(pos => {
            window.pathpalDirections.setOrigin([
              pos.coords.longitude,
              pos.coords.latitude
            ]);
            window.pathpalDirections.setDestination([lng, lat]);
            window.pathpalDirections.route();
          });
        } else {
          window.pathpalDirections.setDestination([lng, lat]);
          window.pathpalDirections.route();
        }

        map.flyTo({ center: [lng, lat], zoom: 14 });
      });
    }

    // Voting logic
    const likeBtn = document.querySelector('.like-btn');
    const dislikeBtn = document.querySelector('.dislike-btn');
    likeBtn?.addEventListener('click', (e) => handleVoteClick(e, 'poi'));
    dislikeBtn?.addEventListener('click', (e) => handleVoteClick(e, 'poi'));
  });
});


    const marker = new mapboxgl.Marker(el).setLngLat([lng, lat]).addTo(map);
    list.push(marker);
    // Open popup on marker click only
    el.addEventListener('click', () => {
      popup.addTo(map).setLngLat([lng, lat]);
    });
  }
}

// 10. ToggleControl Class
class ToggleControl {
  constructor(type, markersArray, onToggle) {
    this.type = type;
    this.markersArray = markersArray;
    this.onToggle = onToggle;
    this.visible = false;
  }
  onAdd(map) {
    this.map = map;
    this.container = document.createElement('div');
    this.container.className = 'mapboxgl-ctrl mapboxgl-ctrl-group';

    const btn = document.createElement('button');
    btn.type = 'button';
    btn.className = 'mapboxgl-ctrl-icon';
    btn.setAttribute('aria-label', `${this.type} friendly`);
    btn.style.backgroundImage = `url(/icons/${this.type}.png)`;
    btn.style.backgroundSize = '24px 24px';
    btn.style.backgroundRepeat = 'no-repeat';
    btn.style.backgroundPosition = 'center';

    btn.addEventListener('click', () => {
      this.visible = !this.visible;
      btn.classList.toggle('active', this.visible);
      this.markersArray.forEach(m =>
        this.visible ? m.addTo(this.map) : m.remove()
      );
      this.onToggle(this.visible);

      if (this.type === 'poi' && !this.visible) {
        // Clear route
        if (window.pathpalDirections?.clear) {
          window.pathpalDirections.clear();
        }

        // Clear input fields
        const inputStart = document.querySelector('#geocoder-start input');
        const inputEnd = document.querySelector('#geocoder-end input');
        if (inputStart) inputStart.value = '';
        if (inputEnd) inputEnd.value = '';

        // Hide error message
        document.querySelector('.directions-error')?.classList.add('d-none');

        // Remove all popups
        document.querySelectorAll('.mapboxgl-popup').forEach(p => p.remove());
      }

      if (this.type === 'poi' && this.visible && navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(pos => {
          const { latitude, longitude } = pos.coords;
          this.map.flyTo({ center: [longitude, latitude], zoom: 14 });
        });
      }
    });

    this.container.appendChild(btn);
    return this.container;
  }
  onRemove() {
    this.container.remove();
    this.map = null;
  }
}

// 11. Global Event Delegation & Exports
document.addEventListener('click', async (e) => {
  const likeBtn = e.target.closest('.like-btn');
  const dislikeBtn = e.target.closest('.dislike-btn');

  if (likeBtn || dislikeBtn) {
    const btn = likeBtn || dislikeBtn;
    const type = btn.dataset.type || 'poi';
    await handleVoteClick(e, type);
  }
});

window.applyPOITargetFromURL = applyPOITargetFromURL;
window.autoFillEndInputFromURL = autoFillEndInputFromURL;



