/**
 * @file themeAuto.js
 * @project PathPal App
 * @description Automatically synchronizes the app’s HTML theme attribute with the user’s OS color scheme
 * when the user preference is set to “system.”
 * @ai Use: This file leverages AI as a learning tool. Portions of this code were generated by AI
 * and subsequently modified to align with PathPal’s design and functionality requirements.
 * @author PathPal Team
 *
 * Sections:
 *   1. System Theme Updater
 *   2. OS Preference Listener
 *   3. Initial Theme Check on Load
 */
(function () {
  /** 1. System Theme Updater
  * Reads the saved theme preference from localStorage. If set to "system",
  * queries the OS color-scheme setting and updates <html data-theme> accordingly.
  */
  function updateSystemTheme() {
    const theme = localStorage.getItem('theme') || 'system';
    if (theme !== 'system') return;
    const dark = window.matchMedia('(prefers-color-scheme: dark)').matches;
    const html = document.documentElement;
    const current = html.getAttribute('data-theme');
    const next = dark ? 'dark' : 'light';
    if (current !== next) {
      html.setAttribute('data-theme', next);
    }
  }

  /** 2. OS Preference Listener
   * Watches for changes in the OS color scheme and triggers updateSystemTheme
   * when the user preference is "system."
   */
  const mql = window.matchMedia('(prefers-color-scheme: dark)');
  mql.addEventListener('change', updateSystemTheme);

  /** 3. Initial Theme Check on Load
  * Applies the correct theme on page load if the preference is "system."
  */
  document.addEventListener('DOMContentLoaded', updateSystemTheme);
})();
